export default {
  login: 'mraditya1999',
  id: 79859996,
  node_id: 'MDQ6VXNlcjc5ODU5OTk2',
  avatar_url: 'https://avatars.githubusercontent.com/u/79859996?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/mraditya1999',
  html_url: 'https://github.com/mraditya1999',
  followers_url: 'https://api.github.com/users/mraditya1999/followers',
  following_url:
    'https://api.github.com/users/mraditya1999/following{/other_user}',
  gists_url: 'https://api.github.com/users/mraditya1999/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/mraditya1999/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/mraditya1999/subscriptions',
  organizations_url: 'https://api.github.com/users/mraditya1999/orgs',
  repos_url: 'https://api.github.com/users/mraditya1999/repos',
  events_url: 'https://api.github.com/users/mraditya1999/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/mraditya1999/received_events',
  type: 'User',
  site_admin: false,
  name: 'Aditya Yadav',
  company: null,
  blog: 'https://www.adityayadav.live',
  location: 'Prayagraj',
  email: null,
  hireable: true,
  bio: "I am a web developer with a passion for creating things that live on the internet. I'm passionate about designing beautiful web Interfaces.",
  twitter_username: 'mraditya1999',
  public_repos: 11,
  public_gists: 0,
  followers: 2,
  following: 2,
  created_at: '2021-03-01T15:55:22Z',
  updated_at: '2023-11-03T20:19:03Z',
};
